language: python
python:
  - 3.6
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
cache: pip
before_install:
  - export DJANGO_SETTINGS_MODULE=ShoppingCart.settings
  - export PYTHONPATH=$HOME/builds/govst-python-team/shopping_cart
  - export PIP_USE_MIRRORS=true
install:
  - pip install -r requirements.txt --quiet
script:
  - python manage.py test
  - coverage run --source=shop,cart manage.py test
after_success:
  - coveralls
